# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://kevin850115.github.io
date_format: "ordinal"
title: 神码
subtitle: "致良知"
description: "神码的个人博客"
keywords: 神码, Code Of Shen
timezone: Asia/Beijing
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Shenyue
organization:
organization_url:
github_username: kevin850115
location: Beijing, China
email: yefeng850115@qq.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: kevin850115/kevin850115.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username:
# https://imsun.net/posts/gitment-introduction/
gitment:
    owner: kevin850115
    repo: kevin850115.github.io
    oauth:
        client_id: 34010936c241325c9485
        client_secret: 885cd711137a1b4dd766c216117bddd097f818d5
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: kevin850115
    repo: kevin850115.github.io
    clientID: 34010936c241325c9485
    clientSecret: 885cd711137a1b4dd766c216117bddd097f818d5
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
